version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './db:/var/lib/postgresql/data'
    container_name: db_0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
