version: '3.3'

services:
  db:
    restart: always
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './db:/var/lib/postgresql/data'
    container_name: db_0
    networks:
      - app-network
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api_0
    ports:
      - '5000:5000'
    entrypoint: bash api-init.sh

networks:
  app-network:
    driver: bridge
